
version: '3'

services:
  api:
    build: 
      context: ./api
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: 
      context: ./frontend
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
    stdin_open: true
    tty: true

