
version: '3'

services:
  api:
    image: 511277412354.dkr.ecr.ap-southeast-2.amazonaws.com/hearthstone-replay-graph:hsgraph-api
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    image: 511277412354.dkr.ecr.ap-southeast-2.amazonaws.com/hearthstone-replay-graph:hsgraph-client
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - NODE_ENV=production

    ports:
      - '80:80'
    tty: true


